Config object integration
hyperledger-labs/SmartBFT pull request #314
Opened 2019-09-01 13:39 UTC by tock-ibm

2019-09-01 15:30 UTC, yacovm commented on pkg/consensus/consensus.go
> +		// TODO return error
Let's please remove the NumberOfNodes from the config. 
This is a plurality of configuration. 

Since we need to get the IDs of the nodes somehow, and currently we get them via the **Nodes()** API call - adding an additional configuration field that returns the number of nodes doesn't give any additional benefit and only makes the code more complex.

Given that we're going to need the **Nodes()** API call for reconfiguration,  it's probably here to stay - something I cannot say about the NumberOfNodes which is probably going to be removed once dynamic reconfiguration will be introduced. 

So let's please remove this field and stick with what we have now.

2019-09-01 15:32 UTC, yacovm commented on test/test_app.go
> +	LeaderHeartbeatTimeout:    4 * time.Second,
This can be risky for tests in CI... we use logical clocks anyway for timeouts when we want it, so i suggest we go to a minute like before.

2019-09-01 15:33 UTC, yacovm commented on test/test_app.go
> +var FastConfig = consensus.Configuration{
any reason this is exported?

2019-09-01 15:34 UTC, yacovm requested changes
Please see comments, especially regarding the number of nodes.

2019-09-02 06:57 UTC, yacovm commented on pkg/consensus/consensus.go
> +		// TODO return error
An alternative way is to also include the nodes in the configuration, and have the configuration be a function instead of a struct instance

2019-09-02 08:30 UTC, tock-ibm commented on pkg/consensus/consensus.go
> +		// TODO return error
I favor the second alternative, have the library be explicitly configured with the identity of nodes.

2019-09-02 08:33 UTC, tock-ibm commented on test/test_app.go
> +var FastConfig = consensus.Configuration{
not really

2019-09-02 08:39 UTC, yacovm commented on pkg/consensus/consensus.go
> +		// TODO return error
Then please add a function that returns a configuration object which contains the list of nodes (ids) and the size can be inferred from that list.

The function is what will be injected to the Consensus instead of the config object itself.

2019-09-02 08:57 UTC, tock-ibm commented on pkg/consensus/consensus.go
> +		// TODO return error
that is not what I meant... I think since we still have no design for reconfiguration the best course of action is to remove NumberOfNodes and address reconfig when we have an issue for that.

2019-09-02 10:16 UTC, tock-ibm commented on test/test_app.go
> +var FastConfig = consensus.Configuration{
Done

2019-09-02 10:17 UTC, tock-ibm commented on test/test_app.go
> +	LeaderHeartbeatTimeout:    4 * time.Second,
Done

2019-09-02 10:18 UTC, yacovm submitted a review, later dismissed

2019-09-02 10:28 UTC, yacovm approved these changes

2019-09-02 10:28 UTC, merged

2019-09-02 10:30 UTC, tock-ibm commented
#298