blocking sync in view changer
hyperledger-labs/SmartBFT pull request #326
Opened 2019-09-05 12:56 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2019-09-05 14:26 UTC, yacovm commented on internal/bft/viewchanger.go
> +		select { // wait for sync to return with expected info
I think you should also wait for startChangeChan for completeness, just to un-block anyone that is invoking StartViewChange.

2019-09-05 14:27 UTC, yacovm requested changes
Please see comment in the code + maybe we should add a test in the **view_changer_test.go** for this,

2019-09-05 14:32 UTC, HagarMeir commented
I can add unit tests on Sunday

2019-09-08 09:18 UTC, yacovm commented on internal/bft/viewchanger_test.go
> +	synchronizerWG.Add(2)
why is it safe to add the counter when the view changer operates in a different goroutine?

2019-09-08 09:19 UTC, yacovm commented on internal/bft/viewchanger_test.go
> +	vc.HandleMessage(1, msg)
can you perhaps add some comments to give background what is the scenario, what is the expected behavior, etc?

2019-09-08 09:22 UTC, yacovm commented on internal/bft/viewchanger.go
> +		case info := <-v.informChan:
if you read from **informChan** don't you also need to call **v.informNewView(info)** ?

2019-09-08 10:50 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		case info := <-v.informChan:
this is why I added a TODO later
`// TODO what if view is bigger than expected?`
it won't be simply calling the `informNewView`
and I will deal with this in a later PR

2019-09-09 08:06 UTC, yacovm approved these changes

2019-09-09 08:06 UTC, merged