In flight
hyperledger-labs/SmartBFT pull request #335
Opened 2019-09-09 14:03 UTC by HagarMeir

2019-09-14 08:52 UTC, yacovm commented on internal/bft/viewchanger.go
> +			panic(fmt.Sprintf("Node was unable to unmarshal the in flight proposal metadata, error: %v", err))
this is a message a remote node sends you, no? So why panic? Just skip it.

2019-09-14 08:53 UTC, yacovm commented on internal/bft/viewchanger.go
> +			if vd.InFlightProposal.Metadata == nil {
isn't this a message that a remote node sends you? Not sure you should panic here and in line 631

2019-09-14 08:57 UTC, yacovm commented on internal/bft/viewchanger.go
> +	noInFlightConut := 0
noInFlightConut --> noInFlightCount or noInFlightCoconut

2019-09-14 08:59 UTC, yacovm commented on internal/bft/viewchanger.go
> +		if vd.InFlightProposal.Metadata == nil { // should have been validated earlier
It's true, but this is an exported function, so either un-export it, or don't panic.

2019-09-14 09:00 UTC, yacovm commented on internal/bft/viewchanger.go
> +		if err := proto.Unmarshal(vote.GetViewData().RawViewData, vd); err != nil {
general rule of thumb: never panic upon input from an external source.

2019-09-14 09:18 UTC, yacovm commented on internal/bft/viewchanger.go
> +		if inFlightMetadata.LatestSequence == expectedSequence { // this is the expected in flight proposal sequence
once we passed: **if inFlightMetadata.LatestSequence != expectedSequence** above, then it also means if **inFlightMetadata.LatestSequence == expectedSequence**  so no reason to check once more.

2019-09-14 09:19 UTC, yacovm commented on internal/bft/viewchanger.go
> +			if vd.InFlightPrepared { // this proposal is prepared and so it is possible
easier to check the inverse and then continue instead of having another indentation.

2019-09-14 09:24 UTC, yacovm commented on internal/bft/viewchanger.go
> +	for _, vd := range messages {
as a general rule of thumb - you just iterated over messages before, and did all kinds of validations.

Why not create a custom data structure (map, slice) that holds the distilled types you validated previously, so you don't need to validate again?

2019-09-14 09:29 UTC, yacovm commented on internal/bft/viewchanger.go
> +					if isSameProposals(p.proposal, vd.InFlightProposal) {
how about creating a histogram (map) from a digest (string) to a list of proposals? 
Then you can easily pick the proposal that is pre-prepared, no?

2019-09-14 09:31 UTC, yacovm commented on internal/bft/viewchanger.go
> +func isSameProposals(p1, p2 *protos.Proposal) bool {
this can be replaced by proto.Equal()

2019-09-14 09:31 UTC, yacovm commented on internal/bft/viewchanger.go
> +func isEqualBytes(a, b []byte) bool {
can be replaced by **bytes.Equal**

2019-09-14 09:34 UTC, yacovm commented on internal/bft/viewchanger.go
> +			panic(fmt.Sprintf("Node was unable to validate last decision in viewData message, error: %v", err))
I don't think we should panic in exported functions such as these. We can return an error instead.

2019-09-14 09:36 UTC, yacovm commented on internal/bft/viewchanger.go
> +		err, seq := ValidateLastDecision(vd, quorum, N, verifier)
Now that I look at it... we should really switch the order of the return arguments here. should have caught it in CR :/

2019-09-14 09:50 UTC, yacovm commented on internal/bft/viewchanger.go
> +	// the in flight proposal view asked to sync
can we sync in the view but not complain? only in discoverIfSyncNeeded but it shouldn't be able to get there at all if we abort the view inside **Decide**.

2019-09-14 09:51 UTC, yacovm commented on internal/bft/viewchanger.go
> +	v.Application.Deliver(proposal, signatures)
Let's first abort the view, since it did its job, no?

2019-09-14 09:54 UTC, yacovm requested changes
Good work overall, comments inside.

2019-09-15 07:33 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +			panic(fmt.Sprintf("Node was unable to unmarshal the in flight proposal metadata, error: %v", err))
Well the thing is that this message was validated earlier and if we got here we know it should be ok. If not then something is really wrong. 
There is also a comment: `// should have been validated earlier`

2019-09-15 07:36 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +			if vd.InFlightProposal.Metadata == nil {
see my reply above

2019-09-15 07:38 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		if vd.InFlightProposal.Metadata == nil { // should have been validated earlier
I exported it so I could test it. So I guess I'll return an error and deal with it later in the code.

2019-09-15 07:58 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		if vd.InFlightProposal.Metadata == nil { // should have been validated earlier
Or I could un-export it and check it in a separate test file that is a part of the same package?

2019-09-15 07:59 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		if err := proto.Unmarshal(vote.GetViewData().RawViewData, vd); err != nil {
again was validate before reaching here so shouldn't happen

2019-09-15 08:08 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +			panic(fmt.Sprintf("Node was unable to validate last decision in viewData message, error: %v", err))
same as before...

2019-09-15 08:09 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		err, seq := ValidateLastDecision(vd, quorum, N, verifier)
why?

2019-09-15 08:10 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +	// the in flight proposal view asked to sync
Yes we sync here and not complain...
If this view complains then it will cause a panic...

```
func (v *ViewChanger) Complain(viewNum uint64, stopView bool) {
	v.Logger.Panicf("Node %d has complained while in the view for the in flight proposal", v.SelfID)
}
```

2019-09-15 08:16 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +	v.Application.Deliver(proposal, signatures)
In theory you are right
But the view is now busy with deciding so if I try to abort here the abort waits for the view to finish and we get a deadlock

2019-09-15 10:32 UTC, yacovm commented on internal/bft/viewchanger.go
> +		if vd.InFlightProposal.Metadata == nil { // should have been validated earlier
returning an error is best i think

2019-09-15 10:33 UTC, yacovm commented on internal/bft/viewchanger.go
> +		if err := proto.Unmarshal(vote.GetViewData().RawViewData, vd); err != nil {
can you point me where?

2019-09-15 10:33 UTC, yacovm commented on internal/bft/viewchanger.go
> +		err, seq := ValidateLastDecision(vd, quorum, N, verifier)
because in golang you return the error last, not first

2019-09-15 10:35 UTC, yacovm commented on internal/bft/viewchanger.go
> +	v.Application.Deliver(proposal, signatures)
you can use **stop()**, no?

2019-09-15 11:36 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		if vd.InFlightProposal.Metadata == nil { // should have been validated earlier
ok will do

2019-09-15 11:36 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		if err := proto.Unmarshal(vote.GetViewData().RawViewData, vd); err != nil {
```
//viewData message
	if vd := m.GetViewData(); vd != nil {
		v.Logger.Debugf("Node %d is processing a view data message %s from %d", v.SelfID, MsgToString(m), sender)
		if !v.validateViewDataMsg(vd, sender) {
			return
		}
		v.viewDataMsgs.registerVote(sender, m)
		v.processViewDataMsg()
		return
	}
```

2019-09-15 11:37 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +		err, seq := ValidateLastDecision(vd, quorum, N, verifier)
alright

2019-09-15 12:12 UTC, HagarMeir commented on internal/bft/viewchanger.go
> +					if isSameProposals(p.proposal, vd.InFlightProposal) {
to get a digest I need to convert to types.proposal
is it worth it?

2019-09-15 14:05 UTC, closed without merging