state transfer on sync
hyperledger-labs/SmartBFT pull request #358
Opened 2019-09-22 11:14 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2019-09-22 11:19 UTC, HagarMeir commented
https://github.com/SmartBFT-Go/consensus/issues/350

2019-09-22 11:35 UTC, yacovm commented on internal/bft/controller.go
> +			view = response.View
in case of a view change, the nodes that changed the view - write the view change metadata to WAL. 
This node, however - doesn't. 
Shouldn't we write it to WAL as well as soon as we successfully detect the view has increased without the seqNum being increased, to mimic what the rest of the cluster does?

2019-09-22 11:36 UTC, yacovm commented on internal/bft/controller_test.go
> +		CollectTimeout: 10 * time.Millisecond,
I'd increase this to a few seconds.

2019-09-22 11:38 UTC, yacovm commented on internal/bft/controller.go
> +	response := c.Collector.CollectStateResponses()
the CollectStateResponses drains the message channel before receiving, isn't that a problem? 
You might get a response as you drain the channel in tests.
I think that you should actually drain the channel as you aggregate the responses, at the end of CollectStateResponses and not at its beginning.

2019-09-22 11:39 UTC, yacovm commented on internal/bft/statecollector.go
> +	for len(s.incMsgs) > 0 {
this block can moved to the end of the method, since you are anyway protected by the votes and no one can vote more than once.

2019-09-22 11:42 UTC, yacovm commented on internal/bft/statecollector.go
> +	timer := time.NewTimer(s.CollectTimeout)
you can just defer timer.Stop() here

2019-09-22 11:44 UTC, yacovm commented on internal/bft/statecollector.go
> +			if viewAndSeq := s.collectLogic(); viewAndSeq != nil {
"collectLogic" can perhaps be renamed to something like: "collectedQuorumOfX" when X is either votes, or view attestations, etc.

2019-09-22 11:45 UTC, yacovm commented on internal/bft/statecollector.go
> +	if len(s.responses.voted) > s.f {
you can check the NOT of this and just early return nil, and then reduce indentation for all the function.

2019-09-22 11:45 UTC, yacovm commented on internal/bft/statecollector.go
> +				View: vote.GetStateTransferResponse().ViewNum,
nil check missing

2019-09-22 11:47 UTC, yacovm commented on internal/bft/statecollector.go
> +func (s *StateCollector) HandleMessage(sender uint64, m *protos.Message) {
let's check the message type here, and that the inner type isn't nil - just in case.

2019-09-22 11:48 UTC, yacovm commented on internal/bft/statecollector.go
> +				votesMap[viewAndSeq] = count
I think that votesMap[viewAndSeq]++ should work... no?

2019-09-22 11:51 UTC, yacovm commented on pkg/consensus/config.go
> +	// CollectTimeout is the interval after which the node stops listening to StateTransferResponse messages.
Perhaps rephrase to: "The timeout that it takes to collect information about view metadata from remote nodes." ?

2019-09-22 11:52 UTC, yacovm commented on internal/bft/statecollector_test.go
> +func TestBasicTimeout(t *testing.T) {
put parallel ?

2019-09-22 11:52 UTC, yacovm commented on internal/bft/statecollector_test.go
> +	collector.CollectStateResponses()
check the return value is nil?

2019-09-22 11:53 UTC, yacovm requested changes
Did a quick pass, looks good ! 

Some comments below.

2019-09-22 11:54 UTC, yacovm commented on internal/bft/statecollector_test.go
> +		CollectTimeout: 10 * time.Millisecond,
if we put t.Parallel() in the test, you can increase the timeout to avoid flakes

2019-09-22 12:41 UTC, HagarMeir commented on internal/bft/controller.go
> +			view = response.View
good point

2019-09-22 12:42 UTC, HagarMeir commented on internal/bft/controller_test.go
> +		CollectTimeout: 10 * time.Millisecond,
Why? I want there to be a timeout...the faster the better

2019-09-22 12:44 UTC, HagarMeir commented on internal/bft/controller.go
> +	response := c.Collector.CollectStateResponses()
I don't want to handle old responses
in uint tests I wait to see that collection has started by using the log

2019-09-22 12:56 UTC, HagarMeir commented on pkg/consensus/config.go
> +	// CollectTimeout is the interval after which the node stops listening to StateTransferResponse messages.
added it

2019-09-22 13:46 UTC, yacovm requested changes
one last issue :)

2019-09-22 13:58 UTC, yacovm approved these changes

2019-09-23 07:17 UTC, yacovm approved these changes

2019-09-23 07:18 UTC, merged