Leader heartbeat response
hyperledger-labs/SmartBFT pull request #366
Opened 2019-09-24 14:37 UTC by tock-ibm

2019-09-24 16:49 UTC, yacovm commented on internal/bft/controller.go
> +func (c *Controller) OnHeartbeatResponseSync(view uint64) {
Cant we please not add yet another method to the controller which only calls a function that is already exported to other components? Why not just log the below message inside the HBM and just call the Sync instead?

2019-09-24 16:52 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
why the indirection? You want to collect *any* **f+1** responses for **some view** that is a greater view than yours. Why do you care about all the different views?

2019-09-24 16:55 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +func NewHeartbeatMonitor(scheduler <-chan time.Time, logger api.Logger, heartbeatTimeout time.Duration, heartbeatCount int, comm Comm, numberOfNodes uint64, handler HeartbeatTimeoutHandler, syncHandl
can we please collapse it back to have 1 parameter in each line?

2019-09-24 16:56 UTC, yacovm commented on test/test_app.go
> +	RequestBatchMaxInterval:   10 * time.Millisecond,
How is this related to the change?

2019-09-24 16:58 UTC, yacovm commented on test/basic_test.go
> +	sugaredLogger := logger.Sugar()
why do you need this logger? if you want to log test messages you can just use t.Log(), but i don't think we should use this. Please remove.

2019-09-24 16:59 UTC, yacovm commented on test/basic_test.go
> +	data0 = <-n0.Delivered
can't we simplify the test? For instance, we only need 1 extra block, not 2.

2019-09-24 17:00 UTC, yacovm commented on test/test_app.go
> +func (a *App) SetLogLevel(level zapcore.Level) {
I don't think this is used.... if not, please remove

2019-09-24 17:01 UTC, yacovm commented on internal/bft/heartbeatmonitor_test.go
> +	t.Run("leader", func(t *testing.T) {
these 2 tests don't share anything, so I think it's best to extract them into 2 different functions entirely and no make sub-tests.

2019-09-24 17:03 UTC, yacovm requested changes
Did a quick pass

2019-09-24 18:17 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +	senders, exists := hm.hbRespCollector[hbr.View]
What if a malicious node sends you infinite responses? You will end up saving them all, no?

2019-09-25 06:25 UTC, tock-ibm commented on internal/bft/controller.go
> +func (c *Controller) OnHeartbeatResponseSync(view uint64) {
Good idea. 
I need an interface for this so I suggest to unify both calls to the controller in one interface:

type HeartbeatEventHandler interface {
	OnHeartbeatTimeout(view uint64, leaderID uint64)
	Sync()
}
This is implemented by the controller, and also simplifies the construction in consensus.

2019-09-25 06:37 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
We need to detect f+1 **identical** votes, i.e. on the same view, that is for sure.
The problem with the current implementation is that indeed a rogue node can force the old leader to store a lot of entries in the map, e.g. it just sends responses with ever increasing view numbers. This must be prevented, I agree.

2019-09-25 06:38 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +func NewHeartbeatMonitor(scheduler <-chan time.Time, logger api.Logger, heartbeatTimeout time.Duration, heartbeatCount int, comm Comm, numberOfNodes uint64, handler HeartbeatTimeoutHandler, syncHandl
sure

2019-09-25 06:40 UTC, tock-ibm commented on test/test_app.go
> +	RequestBatchMaxInterval:   10 * time.Millisecond,
not really related, but makes sense nevertheless

2019-09-25 06:42 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +	senders, exists := hm.hbRespCollector[hbr.View]
I agree, responded to that above as well.
I will change that.

2019-09-25 06:46 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
Why do we need to detect identical votes? All we need to know is that there is an honest node that its view surpasses you, no?

2019-09-25 06:47 UTC, tock-ibm commented on internal/bft/heartbeatmonitor_test.go
> +	t.Run("leader", func(t *testing.T) {
done

2019-09-25 06:52 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
@HagarMeir  ?

2019-09-25 06:55 UTC, HagarMeir commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
I don't see why they need to be identical and not simply higher.
And to avoid the problem Yoav described we should save a view per sender and not a set per view.

2019-09-25 07:06 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +type heartbeatResponseCollector map[uint64]senderSet
Let's think of it this way - if the leader is sending its view number, in theory - the follower can respond with a bit saying - "my view is higher than yours". 
In such a case, we would need to wait for **f+1** identical bits, right?
So here we are just representing this in a different way (sending the view number itself) but the safety holds in an equivalent way.

2019-09-25 07:48 UTC, tock-ibm commented on test/basic_test.go
> +	sugaredLogger := logger.Sugar()
done

2019-09-25 07:48 UTC, tock-ibm commented on test/basic_test.go
> +	data0 = <-n0.Delivered
done

2019-09-25 07:49 UTC, tock-ibm commented on test/test_app.go
> +func (a *App) SetLogLevel(level zapcore.Level) {
done

2019-09-25 09:30 UTC, tock-ibm commented
pushed a new one

2019-09-25 09:30 UTC, closed without merging