Leader nacks after review
hyperledger-labs/SmartBFT pull request #367
Opened 2019-09-25 09:29 UTC by tock-ibm

Addressed code reviews and rebased on latest master

2019-09-25 09:35 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +		numVotes := histogram[view] // if does not exist, returns 0
histogram[view]++ works just fine, I think.

2019-09-25 09:38 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +		if numVotes >= f+1 {
I don't understand why we really need **f+1** identical view numbers ? 
Why can't we just observe **f+1** attestations that the view number is higher than ours? 
Clearly, if we have Byzantine nodes - they can just all send the same view number that an honest node sent us, so every attack that is possible when we count views higher than our view, is also possible when we count identical views, no?

2019-09-25 10:30 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +		numVotes := histogram[view] // if does not exist, returns 0
It does work.

2019-09-25 10:36 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +		if numVotes >= f+1 {
This argument is convincing.

2019-09-26 13:34 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +	if exists && prevVote == hbr.View {
Why do we care if it exists? If we reached this point then we know that hbr.View > hm.View, so why not always re-write it?

2019-09-26 13:48 UTC, yacovm commented on test/basic_test.go
> +	data0 := <-n0.Delivered
Is this a sanity check? Why not just disconnect the leader upfront without doing transactions prior to the disconnect?

2019-09-26 13:49 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +		hm.logger.Infof("Heartbeat is unexpected, ignoring; Monitor: leader=%d, view=%d; HB: sender: %d, view: %d, seq: %d",
I see that you have combined the 2 cases and now it logs the same thing. The previous code distinguishes between the 2 cases and it logs messages that IMO are more user friendly.

2019-09-26 13:49 UTC, yacovm requested changes
some small nits

2019-10-02 08:14 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +	if exists && prevVote == hbr.View {
done

2019-10-02 08:23 UTC, tock-ibm commented on internal/bft/heartbeatmonitor.go
> +		hm.logger.Infof("Heartbeat is unexpected, ignoring; Monitor: leader=%d, view=%d; HB: sender: %d, view: %d, seq: %d",
The problem is that these two conditions may overlap. Before it didn't matter, because we were not sending Nacks. but now, apart from logging issue, the code is more compact. I will change the log message though, so that it is clear which conditions are violated.

2019-10-02 08:40 UTC, tock-ibm commented on test/basic_test.go
> +	data0 := <-n0.Delivered
Yes, I want to do this after a couple of TXs are already past the first leader.

2019-10-03 07:35 UTC, yacovm approved these changes

2019-10-03 07:35 UTC, merged