sync on future heartbeats
hyperledger-labs/SmartBFT pull request #379
Opened 2019-10-22 14:05 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2019-10-22 14:05 UTC, HagarMeir commented
https://github.com/SmartBFT-Go/consensus/issues/369

2019-10-22 18:30 UTC, yacovm commented on internal/bft/heartbeatmonitor.go
> +	if vs != nil { // initialized
isn't this what the viewActiveButBehindLeader is for ?

2019-10-22 18:30 UTC, yacovm requested changes
Please see comment

2019-10-23 08:10 UTC, yacovm approved these changes

2019-10-23 08:10 UTC, merged