allow submit of new requests when stopped timers
hyperledger-labs/SmartBFT pull request #381
Opened 2019-10-23 10:23 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2019-10-23 10:23 UTC, HagarMeir commented
https://github.com/SmartBFT-Go/consensus/issues/309

2019-10-23 11:18 UTC, yacovm commented on internal/bft/requestpool.go
> +	}
this is executed under the lock, so just check if it's stopped right after acquiring the lock, and return early.

2019-10-23 11:20 UTC, yacovm commented on internal/bft/requestpool.go
>  	stopped        bool
Do we need the stopped now ?

2019-10-23 11:20 UTC, yacovm requested changes
see comments

2019-10-23 13:26 UTC, HagarMeir commented on internal/bft/requestpool.go
> +	}
we don't return....we submit the request with a stopped timer...

2019-10-23 13:27 UTC, HagarMeir commented on internal/bft/requestpool.go
>  	stopped        bool
yes...to know during the submit that the pool is stopped and to stop the new request timer

2019-10-24 08:09 UTC, yacovm approved these changes

2019-10-24 08:09 UTC, merged