Config streamline
hyperledger-labs/SmartBFT pull request #404
Opened 2019-11-17 13:41 UTC by tock-ibm

See #403

2019-11-17 14:07 UTC, HagarMeir commented on pkg/consensus/consensus.go
> +
you also said that we should check if SelfID is within Nodes

2019-11-17 14:08 UTC, HagarMeir commented
https://github.com/SmartBFT-Go/consensus/issues/403

2019-11-18 08:10 UTC, tock-ibm commented on pkg/consensus/consensus.go
> +
True, I'll add that to the issue so that I don't forget. It will be in a future commit - there are a couple more that I plan on - the types, that check, etc.

2019-11-18 12:42 UTC, yacovm commented on internal/bft/requestpool.go
> +	ForwardTimeout    time.Duration
the name of the timeout is supposed to be defined by the operation that is timed out, not by what happens afterwards.

2019-11-18 12:44 UTC, yacovm commented on pkg/consensus/config.go
> +	if !(c.IncomingMessageBufferSize > 0) {
is this an unsigned it? if so it's always > 0, so why not just check equality with 0 ? same for the other uints.

2019-11-18 12:44 UTC, yacovm commented on pkg/consensus/config.go
> +	if !(c.RequestComplainTimeout > 0) {
why not just check if it's <= 0 ?

2019-11-18 12:45 UTC, yacovm requested changes
comments inline

2019-11-19 08:24 UTC, HagarMeir commented on internal/bft/requestpool.go
> +	ForwardTimeout    time.Duration
Maybe change it to:
RequestTimeout  and SecondTimeout
or something like this

2019-11-19 08:25 UTC, HagarMeir commented on pkg/consensus/config.go
> +	if !(c.RequestComplainTimeout > 0) {
This is my original code...
Feel free to change it as you wish

2019-11-19 11:10 UTC, tock-ibm commented on internal/bft/requestpool.go
> +	ForwardTimeout    time.Duration
I don't think there is a rule like that, as long as it is consistent and intuitive, which wasn't the case.

2019-11-19 11:14 UTC, tock-ibm commented on pkg/consensus/config.go
> +	if !(c.IncomingMessageBufferSize > 0) {
I id not change the conditions, they are all the same as they were. This format is preferable because it is "sign proof", it will work even if someone decides to change the type back to int.

2019-11-19 11:14 UTC, tock-ibm commented on pkg/consensus/config.go
> +	if !(c.RequestComplainTimeout > 0) {
same as above

2019-11-19 11:16 UTC, yacovm commented on internal/bft/requestpool.go
> +	ForwardTimeout    time.Duration
This is a configuration, right? So the name of the field should denote what is the thing that times out, and not what happens as a result of a timeout. 
What happens as a result of a timeout, is a detail of the protocol and the user shouldn't be even aware of it.

2019-11-19 11:20 UTC, yacovm approved these changes

2019-11-19 11:21 UTC, merged