[WIP] Add BFT metrics
hyperledger-labs/SmartBFT pull request #483
Opened 2021-12-29 14:41 UTC by muzykantov

2021-12-29 23:19 UTC, yacovm commented on pkg/api/diagnostics.go
> +	l Logger
Why is the logger part of the diagnostics?

2021-12-29 23:19 UTC, yacovm commented on internal/bft/requestpool.go
> +		rp.diag.L().Debugf("Returning batch of %d requests totalling %dB",
why do logging events pass through metrics?

2021-12-30 08:15 UTC, C0rWin commented on pkg/api/diagnostics.go
> +	l Logger
This will be changed and yes, no reason to have logger within diagnostics.

2021-12-30 08:15 UTC, C0rWin commented on internal/bft/requestpool.go
> +		rp.diag.L().Debugf("Returning batch of %d requests totalling %dB",
it should be refactored.

2021-12-30 08:16 UTC, C0rWin requested changes
There is a need to refactor the change to extract logger from Diagnostics and also create abstractions to enable injections of metrics providers into lib

2022-01-03 18:24 UTC, closed without merging