add metrics to consensus
hyperledger-labs/SmartBFT pull request #525
Opened 2023-04-13 09:42 UTC by pfi79

#### wal

- wal_count_of_files

#### requestPool

- pool_count_of_elements
- pool_count_of_fail_add_request
- pool_count_leader_forward_request
- pool_count_timeout_two_step
- pool_count_of_delete_request
- pool_count_of_elements_all
- pool_latency_of_elements

#### blacklist

- blacklist_count
- node_id_in_blacklist

#### consensus

- consensus_reconfig
- consensus_latency_sync

#### view

- view_number
- view_leader_id
- view_phase
- view_proposal_sequence
- view_count_txs_in_batch
- view_decisions
- view_count_batch_all
- view_count_txs_all
- view_size_batch
- view_latency_batch_processing
- view_latency_batch_save

#### viewchanger

- viewchange_current_view
- viewchange_next_view
- viewchange_real_view

2023-04-16 18:57 UTC, C0rWin requested changes
I think it will be much easier if you can split this change into several:

1. One to add metric interfaces
2. Separate commit for each group of metrics


Also, no unit tests are provided to ensure metrics are working and reporting as expected. Could you please take care to add them?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Count of request elements in pool for this channel.",
```suggestion
	Help:         "Number of elements in the consensus request pool.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Count of fail add request in pool for this channel.",
```suggestion
	Help:         "Number of requests pool insertion failure.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Count leader forward request on this channel.",
```suggestion
	Help:         "Number of requests forwarded to the leader.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Count of timeout two step on this channel.",
```suggestion
	Help:         "Number of times requests reached second timeout.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Count of request delete from pool on this channel.",
```suggestion
	Help:         "Number of elements removed from the request pool.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "All of request elements in pool for this channel.",
```suggestion
	Help:         "Total amount of elements in the request pool.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "Latency of request elements in pool for this channel.",
```suggestion
	Help:         "The average request processing time, time request resides in the pool.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +}
Does it have a list of IDs or only one ID? There might be more than one blaklisted node.

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +type MetricsBlacklist struct {
Comment (go-doc)?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +type MetricsRequestPool struct {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +func NewMetricsBlacklist(p *metrics.CustomerProvider) *MetricsBlacklist {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "count consensus reconfig on this channel.",
```suggestion
	Help:         "Number of reconfiguration requests.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "latency sync on this channel.",
```suggestion
	Help:         "An average time it takes to sync node.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +type MetricsConcensus struct {
go-doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +func NewMetricsConcensus(p *metrics.CustomerProvider) *MetricsConcensus {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "number of view on this channel.",
```suggestion
	Help:         "The View number value",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "leader id on this channel.",
```suggestion
	Help:         "The leader id.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "proposal sequence view on this channel.",
```suggestion
	Help:         "The sequence number within current view.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "decisions in view on this channel.",
```suggestion
	Help:         "The number of decisions in the current view.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "phase in view on this channel.",
```suggestion
	Help:         "Current consensus phase.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "count txs in batch on this channel.",
```suggestion
	Help:         "The number of transactions per batch.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "count processed batch on this channel.",
```suggestion
	Help:         "Amount of batched processed.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "count txs all on this channel.",
```suggestion
	Help:         "Total amount of transactions.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +type MetricsView struct {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "size of batch on this channel.",
```suggestion
	Help:         "An average batch size.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "latency batch processing on this channel.",
```suggestion
	Help:         "Amount of time it take to process batch.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	Help:         "latency batch save on this channel.",
```suggestion
	Help:         "An average time it takes to persist batch.",
```

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +func NewMetricsView(p *metrics.CustomerProvider) *MetricsView {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	ch := p.Labels["channel"]
This leaks the notion of the channel into consensus. This is supposed to be hidden and property of the metrics provider side.

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +type MetricsViewChange struct {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +func NewMetricsViewChange(p *metrics.CustomerProvider) *MetricsViewChange {
go doc?

2023-04-16 18:57 UTC, C0rWin commented on internal/bft/metrics.go
> +	ch := p.Labels["channel"]
Same as the comment above about leaking abstraction. This should be hidden within the implementation and metrics provider side.

2023-04-16 18:57 UTC, C0rWin commented on pkg/api/metrics.go
> +type CustomerProvider struct {
go doc

2023-04-16 18:57 UTC, C0rWin commented on pkg/api/metrics.go
> +func NewCustomerProvider(mp Provider, labelValues ...string) *CustomerProvider {
go doc

2023-04-16 18:57 UTC, C0rWin commented on pkg/wal/metrics.go
> +type Metrics struct {
go doc

2023-04-16 18:57 UTC, C0rWin commented on pkg/wal/metrics.go
> +func NewMetrics(p *metrics.CustomerProvider) *Metrics {
go doc

2023-04-17 05:14 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "latency batch save on this channel.",
fix

2023-04-17 05:14 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "latency batch processing on this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "size of batch on this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "count txs all on this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Count of request elements in pool for this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Count of fail add request in pool for this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Count leader forward request on this channel.",
fix

2023-04-17 05:15 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Count of timeout two step on this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Count of request delete from pool on this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "All of request elements in pool for this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "Latency of request elements in pool for this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "count consensus reconfig on this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "latency sync on this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "number of view on this channel.",
fix

2023-04-17 05:16 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "leader id on this channel.",
fix

2023-04-17 05:17 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "proposal sequence view on this channel.",
fix

2023-04-17 05:17 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "decisions in view on this channel.",
fix

2023-04-17 05:17 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "phase in view on this channel.",
fix

2023-04-17 05:17 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "count txs in batch on this channel.",
fix

2023-04-17 05:17 UTC, pfi79 commented on internal/bft/metrics.go
> +	Help:         "count processed batch on this channel.",
fix

2023-04-17 05:22 UTC, pfi79 commented on pkg/wal/metrics.go
> +func NewMetrics(p *metrics.CustomerProvider) *Metrics {
fix

2023-04-17 05:22 UTC, pfi79 commented on pkg/wal/metrics.go
> +type Metrics struct {
fix

2023-04-17 05:24 UTC, pfi79 commented on pkg/api/metrics.go
> +func NewCustomerProvider(mp Provider, labelValues ...string) *CustomerProvider {
fix

2023-04-17 05:24 UTC, pfi79 commented on pkg/api/metrics.go
> +type CustomerProvider struct {
fix

2023-04-17 06:02 UTC, pfi79 commented on internal/bft/metrics.go
> +type MetricsBlacklist struct {
fix

2023-04-17 06:02 UTC, pfi79 commented on internal/bft/metrics.go
> +func NewMetricsBlacklist(p *metrics.CustomerProvider) *MetricsBlacklist {
fix

2023-04-17 06:03 UTC, pfi79 commented on internal/bft/metrics.go
> +type MetricsRequestPool struct {
fix

2023-04-17 06:03 UTC, pfi79 commented on internal/bft/metrics.go
> +type MetricsConcensus struct {
fix

2023-04-17 06:03 UTC, pfi79 commented on internal/bft/metrics.go
> +func NewMetricsConcensus(p *metrics.CustomerProvider) *MetricsConcensus {
fix

2023-04-17 06:25 UTC, pfi79 commented on internal/bft/metrics.go
> +func NewMetricsViewChange(p *metrics.CustomerProvider) *MetricsViewChange {
fix

2023-04-17 06:25 UTC, pfi79 commented on internal/bft/metrics.go
> +type MetricsViewChange struct {
fix

2023-04-17 06:26 UTC, pfi79 commented on internal/bft/metrics.go
> +func NewMetricsView(p *metrics.CustomerProvider) *MetricsView {
fix

2023-04-17 06:26 UTC, pfi79 commented on internal/bft/metrics.go
> +type MetricsView struct {
fix

2023-04-17 11:13 UTC, pfi79 commented on internal/bft/metrics.go
> +	ch := p.Labels["channel"]
fix

2023-04-17 11:13 UTC, pfi79 commented on internal/bft/metrics.go
> +	ch := p.Labels["channel"]
fix

2023-04-17 14:21 UTC, C0rWin commented on internal/bft/util.go
> +
I think you can make it simpler:

```
newBlacklistMap := make(map[uint64]bool, len(newBlacklist))
for _, node := range newBlacklist {
    newBlacklistMap[node] = true
}

for _, node := range bl.nodes {
    var value float64
    if newBlacklistMap[node] {
        value = 1
    } else {
        value = 0
    }

    bl.metricsBlacklist.NodesInBlackList.With(
        bl.metricsBlacklist.LabelsForWith(nameBlackListNodeID, strconv.FormatUint(node, 10))...,
    ).Set(value)
}

```

2023-04-17 14:22 UTC, C0rWin commented on internal/bft/util.go
> +
or

```
newBlacklistMap := make(map[uint64]bool, len(newBlacklist))
for _, node := range newBlacklist {
    newBlacklistMap[node] = true
}

for _, node := range bl.nodes {
    inBlacklist := newBlacklistMap[node]

    bl.metricsBlacklist.NodesInBlackList.With(
        bl.metricsBlacklist.LabelsForWith(nameBlackListNodeID, strconv.FormatUint(node, 10))...,
    ).Set(btoi(inBlacklist))
}

func btoi(b bool) float64 {
    if b {
        return 1
    }
    return 0
}

```

2023-04-17 14:42 UTC, pfi79 commented on internal/bft/util.go
> +
fix

2023-04-17 20:28 UTC, C0rWin commented on internal/bft/requestpool.go
> +		rp.metrics.CountOfFailAddRequestToPool.Add(1)
IMO, we need to distinguish between failures cause they might be symptoms of different issues.

2023-04-17 20:37 UTC, pfi79 commented on internal/bft/requestpool.go
> +		rp.metrics.CountOfFailAddRequestToPool.Add(1)
I can label it.

2023-04-18 19:06 UTC, pfi79 commented on internal/bft/requestpool.go
> +		rp.metrics.CountOfFailAddRequestToPool.Add(1)
added the labels

2023-04-30 13:37 UTC, closed without merging