fix error prevs commit
hyperledger-labs/SmartBFT pull request #599
Opened 2024-10-11 15:40 UTC by pfi79

2024-10-11 15:53 UTC, yacovm requested changes
1. Can you add a commit message? 
2. Can you please add a test that checks that when we send pre-prepare, we don't only attach the previous commit signatures when periodical leader rotation is enabled?

2024-10-13 17:13 UTC, pfi79 commented
> 1. Can you add a commit message?
> 2. Can you please add a test that checks that when we send pre-prepare, we don't only attach the previous commit signatures when periodical leader rotation is enabled?

done

2024-10-13 17:40 UTC, yacovm commented on internal/bft/view_test.go
> +				fmt.Println("Sending", args.Get(0))
please remove the print

2024-10-13 18:18 UTC, pfi79 commented on internal/bft/view_test.go
> +				fmt.Println("Sending", args.Get(0))
Ugh, my inattention.

Fixed it.

2024-10-13 18:37 UTC, yacovm approved these changes

2024-10-13 18:37 UTC, merged